### ISSUE TITLE
TLS Session terminates abnormally - TLS1.2 not available.

### ISSUE THREAD

**Issue by mpking828** [rnwood/smtp4dev#330] opened 2020-04-16 15:29 UTC
First of all, thanks for providing this.  Looking to use this to do automated CI Build pipeline tests.

Second, not sure if this from my client, or from smtp4dev (always a risk) but my code does work with commercial mail servers.

When I enable STARTTLS on my client, smtp4dev throw this exception in the WebUI.

System.IO.IOException: Authentication failed because the remote party has closed the transport stream. at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest) --- End of stack trace from previous location where exception was thrown --- at System.Net.Security.SslStream.ThrowIfExceptional() at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result) at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult) at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__68_2(IAsyncResult iar) at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at Rnwood.SmtpServer.Extensions.StartTlsVerb.<>c__DisplayClass0_0.<<Process>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Rnwood.SmtpServer.TcpClientConnectionChannel.ApplyStreamFilter(Func`2 filter) at Rnwood.SmtpServer.Connection.ApplyStreamFilter(Func`2 filter) at Rnwood.SmtpServer.Extensions.StartTlsVerb.Process(IConnection connection, SmtpCommand command) at Rnwood.SmtpServer.Connection.ProcessAsync()

My client has been "hardened" and part of it disables all protocols except for TLS1.2.... Just throwing that out there since it's usually a problem for us with other things.

Found this, seems to agree:
https://github.com/dotnet/runtime/issues/15856
Less tls1.2, more cipher suites.

**Comment by rnwood** [comment] 2020-04-16 15:37
Hi

The most likely cause is the auto-generated cert not being trusted by 
the client.
There's some guidance on where to find this printed to the console when 
the app starts up.

Are you able to confirm from the client logs/output if this is the 
reason it's closing the connection?

Rob
------ Original Message ------

**Comment by mpking828** [comment] 2020-04-16 18:39
It's not the certificate.  I loaded it on the box, added it to the local computer trust store.  Did that before I posted.

But the client logs was a good call.  My email client code threw this error:
Swallowing exception: System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm.

I used NARTAC software's IIS Crypto app to compare the TLS and Cipher suites.  They DO have matches.  (TLS_RSA_WITH_AES_128_CBC_SHA is the shortest to type, but there are about 22 that are the same on both sides.)  But that is just the base OS.

Googling the error gets me:
https://stackoverflow.com/questions/26742054/the-client-and-server-cannot-communicate-because-they-do-not-possess-a-common-a

Which has this reference:

> There are several other posts about this now and they all point to enabling TLS 1.2. Anything less is unsafe.
> 
> You can do this in .NET 3.5 with a patch.
> You can do this in .NET 4.0 and 4.5 with a single line of code
> 
> ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; // .NET 4.5
> ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072; // .NET 4.0
> In .NET 4.6, it automatically uses TLS 1.2.
>See here for more details: .NET support for TLS https://blogs.perficient.com/2016/04/28/tsl-1-2-and-net-support/

So, what version of .NET is this app built in?  (This is built in .NET, right? otherwise I'm not being helpful)

**Comment by mpking828** [comment] 2020-04-17 19:48
I've confirmed it's a Cipher / TLS thing.

I un-hardened my box, and enabled all ciphers / Encryption methods.  Email SSL worked fine.

I reran the hardening script, and it fails again.

Any idea how I can move this further along?  It's pretty standard stuff now to disable all the old encryption methods and ciphers.

**Comment by rnwood** [comment] 2020-04-19 06:28
Thanks for the detailed report. 

I can confirm that this is because TLS1.2 was not enabled. This is for historical reasons because the code where the TLS/SSL versions are selected dates from when we had to opt in to get TLS1.0, and I did not pick this up when porting to .NET Core.
I will fix this by moving to allow the OS to pick, which is an option that has been added since then.

**Comment by rnwood** [comment] 2020-07-03 10:34
This should be resolved in the latest version however please note that appsettings.json turns TlsMode to 'none' by default now. This is because it breaks some clients until people trust the cert and get Hostname in settings correct.
See the instructions on start up to re-enable either implicit TLS or STARTTLS.

**Comment by rnwood** [comment] 2020-07-03 11:40
The E2E tests are now using TLS1.2 over STARTTLS and seems to show this is working fine.

**Closed by rnwood** 2020-07-03 11:40 UTC
