### ISSUE TITLE
EHLO command not returning correct responses

### ISSUE THREAD

**Issue by anthonyvdotbe** [rnwood/smtp4dev#97] opened 2019-03-04 08:57 UTC
I'm having the same issue as described in #5 : the server's EHLO response contains lines like:

> 8BITMIME
SIZE

instead of:

> 250-8BITMIME
250-SIZE

**Comment by rnwood** [comment] 2019-03-04 09:07
Thanks for reporting. This looks like a duplicate of #62. Please can you confirm which platform you're using so we can confirm that?

**Comment by anthonyvdotbe** [comment] 2019-03-04 09:14
Yes, I'm using the Docker Linux image (sorry I forgot to mention that in the report), so this is indeed a duplicate of #62.

**Closed** 2019-03-04 09:15 UTC
