### ISSUE TITLE
[Feature] Make app basepath configurable

### ISSUE THREAD

**Issue by koen-serneels** [rnwood/smtp4dev#405] opened 2020-07-29 10:30 UTC
Hi. I have smtp4dev deployed on a host "smtp4dev-host" exposed via a reverse proxy on "proxy-host" and path "/smtp4dev". When starting smtp4dev it seems to deploy to the root ("/") by default. So, in this case I need to map "http://proxy-host/smtp4dev" to "http://smtp4dev-host/".This would require more than URL rewriting (certain links inside the html are absolute etc) to get it working properly. It would be easier if we could just let smtp4dev be deployed in a given base path (and that all internal links are relative to this base path) so that it could match the proxy path in my case, making it one on one: "http://proxy-host/smtp4dev"  to "http://smtp4dev-host/smtp4dev". Even better would be if this could be some kind of parameter or env var so it can be passed along via docker as well.

I already found this: https://github.com/dotnet/aspnetcore/issues/2302 in which they seem to have introduced ASPNETCORE_BASEPATH (for the app specifically?) and set it via context.Request.PathBase = basePath. This way we could start the ocntainer with something like: `docker run -p 3000:80 -p 2525:25 -e "ASPNETCORE_BASEPATH=smtp4dev" rnwood/smtp4dev:v3`

Would anything like this be possible? Thanks!

**Comment by bberenberg** [comment] 2020-07-29 15:54
Funny that this came in 5 hours ago. I am trying to do the exact same thing!

**Comment by rnwood** [comment] 2020-09-08 13:22
Thanks for submitting this. This is a duplicate of #332. An option for this is already there but due to a regression is currently non functional.

**Closed by rnwood** 2020-09-08 13:22 UTC
