### ISSUE TITLE
[Bug] View tab shows wrongly decoded message for "just send 8 bit" sessions.

### ISSUE THREAD

**Issue by cheoAlejo** [rnwood/smtp4dev#170] opened 2019-08-29 18:00 UTC
When I send a message with latin characters from a file with encoding iso-8859-1 (Western/Windows1252), the "View" tab doesn't show those characters:

My file:

![image](https://user-images.githubusercontent.com/10518807/63963459-b2f85f80-ca5a-11e9-8a31-1646577f8d70.png)

smtp4dev View tab:

![image](https://user-images.githubusercontent.com/10518807/63963521-d6bba580-ca5a-11e9-8c2c-fcc7a9413f53.png)

But the Parts > Source tab does show them correctly:

![image](https://user-images.githubusercontent.com/10518807/63963599-04085380-ca5b-11e9-90f0-faf9e9e6b84f.png)

The charset of the message:

![image](https://user-images.githubusercontent.com/10518807/63963884-8f81e480-ca5b-11e9-8a8e-de2e50992884.png)

# Tech specs

* smtp4dev version: 3.1.0-ci0752
* Browser: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by rnwood** [comment] 2020-02-19 18:01
Thanks for reporting this issue and include enough details to repro.

**Comment by jafin** [comment] 2021-05-08 06:11
Hi @cheoAlejo 

First a disclaimer, I am quite green with internationalization and it appears to be a minefield.

Anyhow,  trying to research this and came across https://stackoverflow.com/questions/25710599/content-transfer-encoding-7bit-or-8-bit

I may of taken this out of context, but are they suggesting 8bit encoding transfer is actually not legal (not recommended) on the  internet?

> As of the publication of this document, there are no standardized Internet transports for which it is legitimate to include unencoded 8-bit or binary data in mail bodies. Thus there are no circumstances in which the "8bit" or "binary" Content-Transfer-Encoding is actually legal on the Internet.

Is there any way you can set Body transfer encoding to `QuotedPintable` instead of `8Bit` ?   
I did up a test scenario, and when I change encoding to QuotedPrintable it is shown correctly.

![image](https://user-images.githubusercontent.com/127927/117528842-9d04b580-b017-11eb-8996-178b4f08dbf1.png)

![image](https://user-images.githubusercontent.com/127927/117528849-a726b400-b017-11eb-9d42-a628569589d9.png)

**Comment by anuj2nt** [comment] 2021-11-06 13:02
This issue is preventing us from using this awesome tool for a while now. Is there any temporary workaround for this ?

**Comment by jafin** [comment] 2022-05-14 13:30
@anuj2nt are you able to supply a test client that creates the email? PHP,js or c#?  Happy to investigate further just after some sample code to produce the email?

**Comment by rnwood** [comment] 2024-03-06 21:07
Repro:
```
using System.Net.Mail;
using System.Net.Mime;
using System.Text;

var smtpClient = new SmtpClient("localhost")
            {
                Port = 25,
            };

            var mailMessage = new MailMessage
            {
                From = new MailAddress("latin.test@mailinator.com"),
                Subject = "Latin test",
                //BodyTransferEncoding = TransferEncoding.,
                Body =
                    "<span>Homines in indicaverunt nam purus quáestionem sentiri unum. Afflueret contentus diam errore faciam, honoris mucius omnem pélléntésqué reiciendis. Acuti admissum arbitrantur concederetur dediti, ferrentur fugiendus inferiorem peccant ponti quando solam ullius. áb atilii concursio constituamus, définitioném diligenter graeci illam máius operis opinionum pótióne versatur. Alliciat aspernari consoletur disserunt, impendere interiret reliquarum verum. Convállis essent foedus gravida iustioribus, mox notissima perpaulum praeclare probatum, prohiberet sensibus. Condimentum efficeretur iis insipientiam, inutile logikh ne ornare, paulo primis primo pugnare putarent quiddam reperiuntur. \r\nCéramico cónsistat éiusdém licet offendimur, recusandae referendá. Cupiditatés hónesta musicis possent, respondendum sollicitudines. Breviter democrito dolor electram illa, ludicra non occulta pérféréndis principio servare suum tranquillitatem. Consentinis probatus qualisque tollatur veritatis. In inséquitur ortum pertinaces, sentit stoici sum téréntii.</span>",
                BodyEncoding = Encoding.Latin1,
                BodyTransferEncoding = TransferEncoding.EightBit,
                IsBodyHtml = true,
            };
            mailMessage.To.Add("latin.test@mailinator.com");

            smtpClient.Send(mailMessage);
```

Unfortunately I fear this is a very complex issue that lies in Rnwood.Smtp4dev server. SMTP4DEV does support 8BITMIME extension and UTF8 but the client is not using it in this case. What is happening is SmtpClient is doing "just-send-8bit" and is encoding the body using whatever encoding is specified. Unfortunately I don't think we're handling that correctly and the body ends up re-encoded as UTF-8. Then when the UI later displays the message, it is reading the Mime-Type header from the body and decoding it using that encoding., but actually it's not encoded like that any more. This is what causes the broken characters.

In the linked PR, I have applied a workaround whilst I think about how to resolve this. The main issue I have is that I'm not sure what is the correct (or most common) behaviour that should be implemented for the "just send 8" case is - What encoding should be used for the body or should it just be treated as a stream of bytes? (this would be a major change to resolve).

The workaround simply avoids this re-encoding in the UI and treats it at UTF8 - which it is. This is not the correct fix though. A build should be generated which you can use to confirm.

**Comment by rnwood** [comment] 2024-03-06 21:17
PR #1344

**Comment by rnwood** [comment] 2024-03-06 21:19
Build 3.3.3-ci20240306100 should now be available.

**Comment by rnwood** [comment] 2024-03-07 16:23
Pleased to confirm that I have created https://github.com/rnwood/smtpserver/pull/173 which addresses this issue in the server component. The message will now not be decoded and re-encoded with the wrong encoding in this "just send 8 bit" scenario.

The resulting build then needs to be picked up by Smtp4dev.

**Comment by rnwood** [comment] 2024-03-09 12:35
The PR has now been updated with what I think is a quite complete fix. The source and raw tabs have also been adjusted to detect the encoding from the relevant MIME part and transcode to UTF8 for display.

Please note, existing message may display strangely since those have already been transcoded incorrectly.

PR will be merged.
Feedback invited for >= 3.3.3-ci20240309103

**Comment by rnwood** [comment] 2024-03-10 16:09
@ballaballaballa Can you share the correct text for the body?

**Comment by rnwood** [comment] 2024-03-10 21:26
I've tested åäö with a variety of encodings including just-send-8-bit iso-8859-1 and I can't reproduce it.

If we take this word as an example from what you are seeing:
> JadÃ¥

In ISO-8859-1 (which is what the part claims to be encoded as), this is encoded as

Ã => 0xc3
¥ => 0xa5

But if we look at UTF-8, 0xc3 0xa5 is å

It should be 0xe5 for ISO-8859-1. So actually, the content of this message is UTF-8 I believe. We need to determine if this is the original client encoding it incorrectly, or if smtp4dev is still doing something wrong.

If you can still reproduce this, would you be able to get a Wireshark trace of the session? This will unambigously show what's going on. Unfortunately, the session log in smtp4dev is text based and we can't see how the chars were encoded as bytes.

**Comment by rnwood** [comment] 2024-04-14 11:41
@ballaballaballa I'm pretty sure that this shows that your client is sending UTF-8 encoded content but declaring it as ISO-8859-1. I believe Wireshark is assuming UTF-8.

Can you select one of the non ASCII chars in Wireshark and see how they have been encoded as bytes. This will confirm it one way or the other.

I'm tempted to add binary session log to smtp4dev to help with complex issues like this.

**Comment by rnwood** [comment] 2024-04-27 14:57
Thanks for the confirmation. Closing this issue now.

**Closed by rnwood** 2024-04-27 14:57 UTC
